### ISSUE TITLE
An extra character is added before the image

### ISSUE THREAD

**Issue by peterhulst** [ttc-freebies/plugin-responsive-images#1] opened 2017-05-19 20:54 UTC
Briljant plugin!

However, an extra character '**Â** ' is added before the image is displayed.

Best regards,

Peter

**Comment by dgt41** [comment] 2017-05-19 22:47
What is the charset of your site and what php version are you running ?
E.g. 
```
<meta charset="UTF-8">
```

**Comment by peterhulst** [comment] 2017-05-20 07:32
I use PHP 7.0.1. 
The Charset is:  charset=utf-8

Best regard.

**Comment by dgt41** [comment] 2017-05-20 11:42
@peterhulst can you test: https://github.com/ttc-freebies/plugin-responsive-images/files/1016124/v1.0.1.zip

**Comment by peterhulst** [comment] 2017-05-20 19:41
@dgt41 Thanx for your quick reply, but the update v1.0.1 does **NOT** fix problem.

**Comment by dgt41** [comment] 2017-05-20 19:43
@peterhulst can you send me the page source of the page that failing at d.grammatiko [at] gmail [.] com ?

**Comment by peterhulst** [comment] 2017-05-20 20:08
I have sent you an example page.

**Comment by dgt41** [comment] 2017-05-21 10:20
I am closing this, as the issue was not caused by this plugin

**Closed by dgt41** 2017-05-21 10:20 UTC
