### ISSUE TITLE
Doesn't work in com_fields

### ISSUE THREAD

**Issue by mediafoks** [ttc-freebies/plugin-responsive-images#566] opened 2023-11-22 18:05 UTC
A custom field in a material, such as an editor. How to make responsive-images work in custom fields?

**Comment by dgrammatiko** [comment] 2023-11-22 18:26
Did you followed the docs: https://responsive-images.dgrammatiko.dev/documentation/layouts/#using-responsive-images-in-layouts ?

Custom Fields need to be help by your layout, the plugin doesn't blindly try to process every image in your HTML output (by design)

**Comment by mediafoks** [comment] 2023-11-23 07:40
> Did you followed the docs: https://responsive-images.dgrammatiko.dev/documentation/layouts/#using-responsive-images-in-layouts ?
> 
> Custom Fields need to be help by your layout, the plugin doesn't blindly try to process every image in your HTML output (by design)

Perhaps I didn't explain the situation accurately.
There is a custom field - "Editor".

![ftest_01](https://github.com/ttc-freebies/plugin-responsive-images/assets/106742407/befff51f-a448-42c5-9ee5-9f555c55d081)

In the material, in this field I insert a picture.

![ftest_02](https://github.com/ttc-freebies/plugin-responsive-images/assets/106742407/11098520-c2ac-4549-a6e4-b9828809d223)

The image is not processed by the plugin.

![ftest_03](https://github.com/ttc-freebies/plugin-responsive-images/assets/106742407/9e3e878d-8fbf-4361-a405-8e394cccc83f)

**Comment by dgrammatiko** [comment] 2023-11-23 16:46
Here's a way to get the images automatically converted:

- create a layout override `templates/cassiopeia/html/layouts/com_fields/field/render.php` (replace cassiopeia with your current template)
- Paste the contents from the snippet bellow

<details>
<summary>`templates/cassiopeia/html/layouts/com_fields/field/render.php`</summary>

```php
<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_fields
 *
 * @copyright   (C) 2016 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Language\Text;

if (!array_key_exists('field', $displayData)) {
    return;
}

$field = $displayData['field'];
$label = Text::_($field->label);
$value = $field->value;
$showLabel = $field->params->get('showlabel');
$prefix = Text::plural($field->params->get('prefix'), $value);
$suffix = Text::plural($field->params->get('suffix'), $value);
$labelClass = $field->params->get('label_render_class');
$valueClass = $field->params->get('value_render_class');

if ($value == '') {
    return;
}

?>
<?php if ($showLabel == 1) : ?>
    <span class="field-label <?php echo $labelClass; ?>"><?php echo htmlentities($label, ENT_QUOTES | ENT_IGNORE, 'UTF-8'); ?>: </span>
<?php endif; ?>
<?php if ($prefix) : ?>
    <span class="field-prefix"><?php echo htmlentities($prefix, ENT_QUOTES | ENT_IGNORE, 'UTF-8'); ?></span>
<?php endif; ?>
<span class="field-value <?php echo $valueClass; ?>"><?php

preg_match_all('#<img\s[^>]+>#', $value, $matches);

if (empty($matches)) {
  echo $value;
} else {
  foreach ($matches[0] as $img) {
    // Make sure we have a src
    if (strpos($img, ' src=') === false || strpos($img, '//') !== false) continue;
    $sizes = [320, 768, 1200];
    $processed = (new \Ttc\Freebies\Responsive\Helper)->transformImage($img, $sizes);
    if ($processed !== $img) {
      echo str_replace($img, $processed, $value);
    }
  }
}
?></span>
<?php if ($suffix) : ?>
    <span class="field-suffix"><?php echo htmlentities($suffix, ENT_QUOTES | ENT_IGNORE, 'UTF-8'); ?></span>
<?php endif; ?>

```

</details>

enjoy:

![Screenshot 2023-11-23 at 18 41 42](https://github.com/ttc-freebies/plugin-responsive-images/assets/3889375/efb85271-3eda-4471-8a9f-1ec6950cec70)

**Comment by mediafoks** [comment] 2023-11-23 17:09
> Here's a way to get the images automatically converted:
> 
> * create a layout override `templates/cassiopeia/html/layouts/com_fields/field/render.php` (replace cassiopeia with your current template)
> * Paste the contents from the snippet bellow
> 
> `templates/cassiopeia/html/layouts/com_fields/field/render.php`
> ```
> <?php
> 
> /**
>  * @package     Joomla.Site
>  * @subpackage  com_content
>  *
>  * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
>  * @license     GNU General Public License version 2 or later; see LICENSE.txt
>  */
> 
> defined('_JEXEC') or die;
> 
> use Joomla\CMS\Factory;
> use Joomla\CMS\HTML\HTMLHelper;
> use Joomla\CMS\Language\Associations;
> use Joomla\CMS\Language\Text;
> use Joomla\CMS\Layout\FileLayout;
> use Joomla\CMS\Layout\LayoutHelper;
> use Joomla\CMS\Router\Route;
> use Joomla\CMS\Uri\Uri;
> use Joomla\Component\Content\Administrator\Extension\ContentComponent;
> use Joomla\Component\Content\Site\Helper\RouteHelper;
> 
> // Create shortcuts to some parameters.
> $params  = $this->item->params;
> $canEdit = $params->get('access-edit');
> $user    = Factory::getUser();
> $info    = $params->get('info_block_position', 0);
> $htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';
> 
> // Check if associations are implemented. If they are, define the parameter.
> $assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
> $currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
> $isNotPublishedYet = $this->item->publish_up > $currentDate;
> $isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
> ?>
> <div class="com-content-article item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
> ......................


The code you wrote is components\com_content\tmpl\article\default.php
How can a material template be inserted into layouts/com_fields/field/render.php??

**Comment by dgrammatiko** [comment] 2023-11-23 18:25
@mediafoks I'm sorry pasted the wrong file contents there, I've updated the comment

**Comment by mediafoks** [comment] 2023-11-23 19:09
Thank you! Everything works great.

**Comment by dgrammatiko** [comment] 2023-12-04 21:46
Shall I close the issue here?

**Closed as completed** 2024-04-02 07:50 UTC
